title:               Zinzy Waleson
include:             ['_pages','_posts','_library','_links']
exclude:             ['_includes/notes_graph.json']
# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-timeago
  - jekyll-archives
  - jekyll-toc

# jekyll-archives:
#   enabled: all
#   layout: archive
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tag/:name/'
#     category: '/category/:name/'

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  notes:
    output: true
    permalink: /:slug 
  links:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_library/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_posts/**/*.md"
    values:
      layout: "post"
  - scope:
      path: "_pages/**/*.md"
    values:
      layout: "page"
  - scope:
      path: "_links/**/*.md"
    values:
      layout: "links"
