title: Zinzy Waleson Geene
tagline: Zinzy Waleson Geene is a researcher, designer, and queer facilitator from Amsterdam.
author:
  name: Zinzy Waleson Geene
  email: zinzy@pm.me

include:
  - My-Digital-Garden
exclude:             
  - _includes/notes_graph.json
  - assets/js/webmention.js
url:                  https://www.zinzy.website
# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-timeago
  - jekyll-archives
  - jekyll-toc
  # - jekyll-feed
  - jekyll-category-pages

# jekyll-archives:
#   enabled: all
#   layout: archive
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tag/:name/'
#     category: '/category/:name/'

sass:
  sass_dir:          _sass
  style:            :compressed



collections_dir: My-Digital-Garden

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  notes:
    output: true
    permalink: /:slug 
    layout: "note"

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "My-Digital-Garden/_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "My-Digital-Garden/_posts/**/*.md"
    values:
      layout: "post"
  - scope:
      path: "_pages/**/*.md"
    values:
      layout: "page" 