title: Zinzy Waleson Geene
description: Zinzy Waleson Geene is a researcher, designer, facilitator, and IndieWeb enthusiast from Amsterdam.
include:
  - My-Digital-Garden
exclude:             
  - _includes/notes_graph.json
  - assets/js/webmention.js
url: https://www.zinzy.website
# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-timeago
  - jekyll-archives
  - jekyll-toc
  - jekyll-paginate
  # - jekyll-feed
  # - jekyll-category-pages


posts_limit: 10
feed:
  path: /feed.xml

paginate: 1
paginate_path: /page/:num/


jekyll-archives:
  enabled:
    - categories
    - tags
  layout: tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

sass:
  sass_dir:          _sass
  style:            :compressed

reading_time:
  second_plural: "sec."    # default: seconds
  minute_singular: "min."  # default: minute
  minute_plural: "min."    # default: minutes

collections_dir: My-Digital-Garden

collections: 
  abcdef:
    output: true
    permalink: /:slug 
  notes:
    output: true
    permalink: /:slug 
    layout: "note"  
  micro:
    output: true
    permalink: /:year/:month/:day/:slug 
  now:
    output: true
    permalink: /:year/:month/:day/:slug
    sort_by: date 
  posts:
    output: true
    permalink: /:year/:month/:day/:slug 

defaults: 
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "My-Digital-Garden/_abcdef/**/*.md"
    values:
      layout: "abcdef" 
  - scope:
      path: "My-Digital-Garden/_micro/**/*.md"
    values:
      layout: "micro"
  - scope:
      path: "My-Digital-Garden/_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "My-Digital-Garden/_now/**/*.md"
    values:
      layout: "now-page" 
  - scope:
      path: "My-Digital-Garden/_posts/**/*.md"
    values:
      layout: "post" 